version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=workopia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: workopia
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./workopia.sql:/docker-entrypoint-initdb.d/workopia.sql

volumes:
  mysql-data:
